### ISSUE TITLE
Invalid torrent identifier

### ISSUE THREAD

**Issue by alessioalex** [mikeal/dropub#6]
When I chose a file it seemed to be loading, but then I looked at the console:

```js
bundle.js:9283 Uncaught Error: Invalid torrent identifier
    at https://dropub.com/bundle.js:13928:10
    at Item.run (https://dropub.com/bundle.js:4806:14)
    at drainQueue (https://dropub.com/bundle.js:4776:42)
```

Latest Chromium on Ubuntu.

**Comment by mikeal** [comment]
What is the full URL?

**Comment by mikeal** [comment]
Try it now, there was a bug where "ref=" being added to the url was breaking it, which would happen if you were linked from a page like product hunt.

**Comment by alessioalex** [comment]
Yep, I got there from Twitter so that must have been it. Fixed now.
