### ISSUE TITLE
Blank page on iOS?

### ISSUE THREAD

**Issue by simevidas** [mikeal/dropub#8]
Safari on iOS just shows a blank page. Is it not supported? Sorry for not debugging this, but I don’t have a Mac, so I’m not able to connect the page to Web Inspector.

**Comment by christopheranderton** [comment]
No problem here (iPhone 6+, iOS 10.3.2). Check if you got any adblockers enabled. Some of them uses really strict filters.

**Comment by simevidas** [comment]
It renders correctly now!
